### ISSUE TITLE
Form validation rules with attributes not working!

### ISSUE THREAD

**Issue by Mircea-Ciuchea** [patrickbrouwers/Laravel-Doctrine#4]
Form validation that uses rules with attributes `'exists:users'` or `'unique:users'` throw this error:
`QueryException in QueryException.php line 63:
[Semantical Error] line 0, col 21 near 'users e WHERE': Error: Class 'users' is not defined.`

**Comment by patrickbrouwers** [comment]
You have to use the entity class name:

`exists:App\User`

**Comment by Mircea-Ciuchea** [comment]
I see I have to put the entity namespace. It works, thanks!

**Comment by patrickbrouwers** [comment]
Yes. It's a better abstracting than to use the table name.
