### ISSUE TITLE
Is this 5.1 ready?

### ISSUE THREAD

**Issue by williamoliveira** [patrickbrouwers/Laravel-Doctrine#5]
I am getting 
`exception 'Brouwers\LaravelDoctrine\Exceptions\DriverNotRegistered' with message 'Driver  not registered' in /my_path/vendor/brouwers/laravel-doctrine/src/Configuration/ExtendableTrait.php:44`

or did I miss some config?

it's a fresh install of Laravel

**Comment by patrickbrouwers** [comment]
Yeah, I'm using it in a 5.1 app.

The fact the exception doesn't show the driver name, means it's trying to resolve a driver with name of an empty string. 

You'll have to check the stack trace to see which one it is, but it probably is cache or database.

This package is going to move to a new repository soon btw: https://github.com/laravel-doctrine/orm.

**Comment by williamoliveira** [comment]
I think i found the problem
 `config('database')` at doctrine.php (the config file) is returning null, it is used at line 23.
I dont know how it works, but I think at that time of execution it was not yet been read

**Comment by patrickbrouwers** [comment]
I don't have any problem with that, strange. 
You can also type the driver name (mysql e.g.) yourseld there, if you can't find out why config fails for you.

**Comment by williamoliveira** [comment]
Yes, I did that for now
