### ISSUE TITLE
Call to undefined method Doctrine\ORM\Mapping\Driver\YamlDriver::addPaths()

### ISSUE THREAD

**Issue by Edwin-Luijten** [patrickbrouwers/Laravel-Doctrine#7]
I am trying yo use the yaml driver and have configured your package to use yaml:
```php
'managers'                  => [
        'default' => [
            'meta'       => 'yaml',
            'connection' => config('database.default'),
            'paths'      => [
                config_path('mappings')
            ],
..........
```

Then, when trying to run doctrine:schema:update
it throws: Call to undefined method Doctrine\ORM\Mapping\Driver\YamlDriver::addPaths()

As far as I have seen, the addPaths() should be in the AbstractFileDriver, but the current doctrine version uses FileDriver to extend the YamlDriver.

Also i'm using ~1.0.0 of your package.

**Comment by jsamhall** [comment]
I am experiencing the same issue when attempting to use the XML driver

**Comment by patrickbrouwers** [comment]
Hello Edwin,

I saw you already found your way to the new Doctrine package (https://github.com/laravel-doctrine/orm)

It's not stable yet, but it's based on this package and it has the fix for the problem you have. I didn't backport it, because of the limited time I have at the moment.
