### ISSUE TITLE
New User Assistance

### ISSUE THREAD

**Issue by bryanrscott** [patrickbrouwers/Laravel-Doctrine#8]
Hi

I am trying to port the example laravel php server implementation of https://github.com/sahat/satellizer.   But I am pretty new to this and just learning.

I have a controller with the function
    /**
     * Get signed in user's profile.
     */
    public function getUser(Request $request)
    {
       $user = EntityManager::find('App\Domain\Entities\User', $request['user']['sub']);
       return $user;
    }

Which is generating the error

[2015-08-20 00:17:48] local.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "object" given.' 

I am guessing it needs to know how to serialise this object.  Would the correct way be to http://symfony.com/doc/current/components/serializer.html  so in laravel I would build a facade for?

**Comment by patrickbrouwers** [comment]
Hello Bryan,

Unlike Eloquent Doctrine entities don't provide magic conversion to JSON.

Returning `$user` will attempt to convert it to a string, which it's unable to without the application telling it how to (like you noted with the serializers).

My go to package for API's (for converting enities/models to JSON array's) is http://fractal.thephpleague.com/ . It more or less provides the same functionality as those Serializers, only it relies on less magic; you will have to tell Fractal which fields you want to convert to JSON.
