### ISSUE TITLE
LaravelNamingStrategy

### ISSUE THREAD

**Issue by cesaric** [patrickbrouwers/Laravel-Doctrine#9]
I'm trying to use **Doctrine\Common\Util\Debug::dump()** and it's erring out.  I'm assuming this needs to be setup in the DoctrineServiceProvider before it can be used?  If not, I'd appreciate any direction.  Thanks!

**Comment by patrickbrouwers** [comment]
Never used it before. How do you try to use it and which exception do you get?

**Comment by cesaric** [comment]
From http://docs.doctrine-project.org/en/latest/tutorials/getting-started.html
  
> Lazy load proxies always contain an instance of Doctrine’s EntityManager and all its dependencies. Therefore a var_dump() will possibly dump a very large recursive structure which is impossible to render and read. You have to use Doctrine\Common\Util\Debug::dump() to restrict the dumping to a human readable level. Additionally you should be aware that dumping the EntityManager to a Browser may take several minutes, and the Debug::dump() method just ignores any occurrences of it in Proxy instances.  

Here's the (3) exceptions:
 
>PDOException in PDOStatement.php line 91: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.first_name' in 'field list'

>PDOException in PDOStatement.php line 93: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.first_name' in 'field list'

>InvalidFieldNameException in AbstractMySQLDriver.php line 71: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.first_name' in 'field list'

If I don't Debug::dump(), everything works fine and I can even var_dump() with no error.  My code is simply: 
```
$entity = $this->em->getRepository(RefState::class)->find(12);
Debug::dump($entity);
```

**Comment by cesaric** [comment]
So it turns out the issue wasn't Debug::dump() but the naming strategy in the DoctrineServiceProvider:
```php
$configuration->setNamingStrategy(
    $this->app->make(LaravelNamingStrategy::class)
);
```
Would it be possible to add this as a configuration in the /config/doctrine.php?

**Comment by patrickbrouwers** [comment]
To disable the laravel naming strategy?

**Comment by cesaric** [comment]
No, I think just allowing which naming strategy class to use would suffice.  So if you wanted to disable the laravel naming strategy, you would just do something like:
```php
$namingStrategy = "Doctrine\ORM\Mapping\DefaultNamingStrategy";
```
This would allow users to wire in their own custom naming strategy classes too.

**Comment by patrickbrouwers** [comment]
In the new Doctrine package which I'm working on `https://github.com/laravel-doctrine/orm`, I've added the option to set a custom naming strategy per manager in the config:

```php
  'managers'                  => [
        'default' => [
            'meta'       => env('DOCTRINE_METADATA', 'annotations'),
            'naming_strategy'=> 'Doctrine\ORM\Mapping\DefaultNamingStrategy'
        ]   
    ]
```

There's no release yet, but I'm working towards it. For now you could try to use `dev-develop`.

**Comment by cesaric** [comment]
I'll do that. Thanks for writing adding that so quick!
